language: node_js
sudo: 'false'
before_script:
- git checkout package-lock.json
env:
  global:
    - secure: wmSM5h6HpDL7+rnd3KqaMNUtU7Rp5jv6P0/5wLJDb3lAtkersEaTrnFa4r8bWmhPq0KOXHcktmHQepatPn+1Ib9iP9RFzwMhM76OiLmV1M+cl8MNfNGRAMljbR9IzyzHzX0UwepPQpMxmc8O3RkF27wm8mCIUmbv9AJWh9adzfZrsErcngc8egrXAJuqiADENCkXUYj7mOP122c2SRD5G8oWA2dgrn6Vqw4vDqikUTxJsGFt/udU7E3xMT/tYPcPiGKKm+xULHZkTkL0l3sObletlI+CNssSE66ygKsYuFiBXVMPh0QbPQo/v3YSYHISszeHPKXMkvZu7x30CYCg6jLHX9mCfjXbd4Al4nu5n58U6Lp+h5ZI/c0iwFqQE9uFwc4/RivQXQAtBUU8vnSoKDtD8bFql8Y9Ki1PX3eTXdRGSARmE9gCOx4rmNT/42GbzXA+vzNRyXWo3IL6sFRjgl7xdsV/Twtl0I+GmUJV0x7LYgQm+P01kT3NmbnYyWe2oHGJGSL/pDqusjT+9oxzniF60qBLSsIlYaC69uY4pklaTCrFdm4eeFFCb8kExA5oDRu42PTd8Ws8tkGVQOi9ZjCK0p9HU5Mi11JfiZd9n2WZ9vSV852V6HE/CMmFvctgIEaBRoHmgLGjvAb7o1JK99MovCT8GSyIBob9NIEhGgA=
    - secure: mOtfFKxTTf+wZA8Wo1LoHlnCceUGVWs2gp0VknivNvxM+ua4hF5WsRQz38Jo3i877ZYDr0hCh9DnhQphAKSs6pn+pmP0iHD1y5gppf12468zOlMRomHs43tTidpH/yS7Bj3eJ1sFrMncWaQdHEkcdxBKPBkVjdzjQ0mu4CfpD3OVsEVWKnbsJSfY82Z8WIg4lLBXtE4l/0M45MRP1mzlAdqHCBBsWEQmKZ0S8p7bBKu6QoIHyUCI2ziMsV+628ExIVBHQn7D+EUCyzg06sidRdytokyukNlhGfigSEV+r2NDPh6NPFAY4eCIN4VKudVjdvqoGlNr5OiDDhvgRdfgPECyqq89EzNWQcFrB/5+pw6TFTvlKQHCTBURTODHMgzTj5MASHm8r/pRDohv1Ux4m8xc59cr197O5KdvsbHiil2BHGX1Bszi1VTrLi1W0lsd6qQMPwuwqxfFYYyjYUNlqRvuceA6IJZJl8XM2eMvFN6MknQR7Lku26003oVMYguDOuJda0UMmpsQnLqOVs1K7p9e047zBf1w9h6qYoDM0+jBA8fu8MF4DulYTfhfjwUSpc1qcoyZ1RJKWL6S+EqyO8EmXR/iuvfGrIgYzXf0DFyj3Lh4JRtLBv+pWzRpCIzrZequfPTTOMkdu5HgRqqYMWQBmJxUj6Mp4ruFVlkNMMM=
node_js: node
addons:
  chrome: stable
  firefox: latest
script:
- xvfb-run npm run test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce; fi
dist: trusty
cache:
  directories:
  - node_modules
